POC/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static


urlpatterns = [
    path('',include('ValidateText.urls')),
    path('admin/', admin.site.urls),
    path('acounts/',include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + staticfiles_urlpatterns()

ValidateText/urls.py
from django.urls import path

from . import views
app_name='ValidateText'

urlpatterns = [
    path('',views.index, name='index'),
    path('analyze/', views.analyze, name='analyze'),
    path('about/', views.about, name='about'),
    path('contactus/', views.contactus, name='contactus'),
    path('Analyze_Text/', views.Analyze_Text, name='Analyze_Text'),

]

accounts/urls.py
from django.urls import path
from . import views


app_name='accounts'

urlpatterns = [
    path('signup/',views.signup_view,name='signup'),
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
]

ValidateText/models.py
from django.db import models

# Create your models here.


class Product(models.Model):
    product_id = models.AutoField
    product_name = models.CharField(max_length=50)
    category = models.CharField(max_length=50,default="")
    subcategory = models.CharField(max_length=50,default="")
    price = models.IntegerField(default=0)
    description = models.CharField(max_length=300)
    pub_date = models.DateField()
    image = models.ImageField(upload_to='product/images',default='')

    def __str__(self):
        return self.product_name

accounts/models.py
from django.db import models

# Create your models here.

ValidateText/views.py
from django.shortcuts import render
from django.http import HttpResponse

from django.contrib.auth.decorators import login_required
# Create your views here.

from .models import Product
from math import ceil

def index(request):
    return render(request,'Home.html')

def about(request):
    products = Product.objects.all()
    p_count = len(products)
    n_slides = p_count//4 + ceil((p_count/4)-(p_count/4))
    params = {'no_of_slides':n_slides,'range':range(1,n_slides),'product':products}
    return render(request,'about.html',params)

def contactus(request):
    return render(request,'contactus.html')

@login_required(login_url="/acounts/login/")
def analyze(request):
    if request.method == 'GET':
        dj_text = request.GET.get('text', 'default')
        puntuation = '~!#$%@^&*()_+=|\/?,<.>[]{}'

        removepunc = request.GET.get('removepunc','off')
        uppercase = request.GET.get('uppercase','off')
        newlineremover = request.GET.get('newlineremover','off')
        extraspaceremover = request.GET.get('extraspaceremover','off')
        analyzed=''
        if removepunc == 'on':
            analyzed = ''
            for char in dj_text:
                if char not in puntuation:
                    analyzed+=char
            dj_text = analyzed

        if uppercase == 'on':
            analyzed = ''
            for char in dj_text:
                analyzed += char.upper()
            dj_text = analyzed

        if newlineremover == 'on':
            analyzed = ''
            for char in dj_text:
                if char != '\n' and char != '\r':
                    analyzed += char
            dj_text = analyzed

        if extraspaceremover == 'on':
            analyzed = ''
            for index, char in enumerate(dj_text):
                if dj_text[index] != int(len(dj_text)):
                    if not(dj_text[index] == ' ' and dj_text[index+1] == ' '):
                        analyzed += char

        if (removepunc != 'on' and uppercase != 'on' and newlineremover != 'on' and extraspaceremover != 'on'):
            context = {
                'Purose': 'No Text Found',
                'text': analyzed
            }
        else:
            context = {
                'Purose': 'Analyzed Text',
                'text': analyzed
            }
        return render(request,'analyze.html', context)


@login_required(login_url="/acounts/login")
def Analyze_Text(request):
    return render(request,'validateText.html')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request,'accounts/signup.html',{'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('ValidateText:index')
    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('ValidateText:index')

ValidateText/templates/Home.html
{% extends 'base.html' %}

{% block title %}
Awesome Blog
{% endblock %}


{% block content %}



<section class="jumbotron text-center">
<div class="container">
    <h1>Welcome to Awsome Blog</h1>
    <p class="lead text-muted">Life is 10% what happens to you and 90% how you react to it.</p>

     <nav>
        {% if user.is_authenticated %}
            <BR>
            <div class="container">

                <div class="list-group">
                      <ul class="list-group">
                          <a href="{% url 'ValidateText:Analyze_Text' %}"> <li class="list-group-item list-group-item-light">Analyze String</li></a>
                          <a href="{% url 'ValidateText:about' %}"><li class="list-group-item list-group-item-light">Product List</li></a>
                          <a href="#"><li class="list-group-item list-group-item-light">Books Library</li></a>
                       </ul>
                </div>
            </div>
        {% else %}
        <a class="btn btn-primary my-2" href="{% url 'accounts:login' %}">LOGIN</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <a class="btn btn-secondary my-2" href="{% url 'accounts:signup' %}">Register</a>
        {% endif %}

     </nav>



</div>
</section>




{% endblock %}

ValidateText/templates/about.html
{% extends 'base.html' %}

{% load static %}


{% block title %}
Abouts us
{% endblock %}



{% block content%}




  <div class="container">
        <div id="demo" class="carousel slide my-3" data-ride="carousel">
            <ul class="carousel-indicators">
              <li data-target="#demo" data-slide-to="0" class="active"></li>

                {% for i in range %}
                    <li data-target="#demo" data-slide-to="{{i}}" ></li>
              {% endfor %}
            </ul>

            <!--Slideshow starts here -->
            <div class="container carousel-inner no-padding">

              <div class="carousel-item active">

                    <div class="col-xs-3 col-sm-3 col-md-3">
                      <div class="card" style="width: 18rem;">
                        <img src='/media/{{ product.0.image }}' class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{ product.0.product_name }}</h5>
                            <p class="card-text">{{ product.0.description}}</p>
                            <a href="https://www.zircon.com/2019/11/26/stud-finder-101-not-all-modes-are-created-equal/" class="btn btn-primary" target="_blank">Add To Cart</a>
                        </div>
                      </div>
                   </div>

                  {% for prods in product|slice:"1:" %}
                  <div class="col-xs-3 col-sm-3 col-md-3">
                      <div class="card" style="width: 18rem;">
                        <img src='/media/{{ prods.image }}' class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{ prods.product_name }}n</h5>
                            <p class="card-text">{{ prods.description}} </p>
                            <a href="https://www.zircon.com/2019/11/26/stud-finder-101-not-all-modes-are-created-equal/" class="btn btn-primary" target="_blank">Add To Cart</a>
                        </div>
                      </div>
                   </div>
                      {% if forloop.counter|divisibleby:3 and forloop.counter > 0 and not forloop.last %}
                        </div>
                                <div class="carousel-item">
                      {% endif %}

                  {% endfor %}
              </div>
            </div>
        </div>
  </div>

    <!-- left and right controls for the slide -->
<br>
   <!--
    <a class="carousel-control-prev" href="#demo" data-slide="prev">
        <span class="carousel-control-prev-icon"></span>
    </a>
    -->
    <a class="carousel-control-next" href="#demo" data-slide="next">
        <span class="carousel-control-next-icon"></span>
    </a>

{% endblock %}

ValidateText/templates/analyze.html
{% extends 'base.html' %}





{% block content %}


        {% if text == '' %}
            <div class="alert alert-warning" role="alert">
                 No Input Text to Analize. Give it a  <a href="{% url 'ValidateText:index' %}" class="alert-link">"click"</a> if you want to re-try.
            </div>
        {% else %}
            <div class="alert alert-success" role="alert">
                <strong>Success</strong> Your Text has been Analyzed..!
            </div>
        {% endif %}


        <div class="container">
            <h1>Your Analyzed Text : {{ Purose }}</h1><br>
            <p><pre>{{ text }}</pre></p>
        </div>


{% endblock %}

ValidateText/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/heading.css' %}">

    <title>{% block title %} {% endblock %}</title>


  </head>


<body>




<div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <a class="navbar-brand" href="/"><img class="logo" src="{% static 'images/headLogo.png' %}"> </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                  <li class="nav-item active">
                    <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'ValidateText:contactus' %}">Contact us</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                  </li>
                </ul>
              </div>

            <div>
                {% if user.is_authenticated %}
                        <form class="form" action="{% url 'accounts:logout' %}" method="POST">
                        {% csrf_token %}
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Logout</button>
                        </form>
                {% else %}
                        <a class="btn btn-primary my-2" href="{% url 'accounts:login' %}">LOGIN</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <a class="btn btn-secondary my-2" href="{% url 'accounts:signup' %}">Register</a>
                {% endif %}

                <form class="form-inline">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
    {% if user.is_authenticated %}

    {% else %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
          <strong>Must Register yourself to view all options......!</strong> You should check in on some of those fields below.
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
    </div>
    {% endif %}
</div>

{% block content %}
{% endblock %}


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

ValidateText/templates/contactus.html
{% extends 'base.html' %}


{% block title %}
Contact Us
{% endblock %}

{% block content %}
    <h1> This is Contact Page </h1>
{% endblock %}

ValidateText/templates/validateText.html
{% extends 'base.html' %}

{% block title %}
Awesome Blog
{% endblock %}


{% block content %}

    <div class="container">

        <div class="list-group">
             <form action="/analyze" method="GET">
             {% csrf_token %}
                <div class="form-group">
                    <label for="exampleFormControlTextarea1">Enter Your Text Here..!</label>
                    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="text"></textarea>
                </div>
                <div class="custom-control custom-switch">
                  <input type="checkbox" class="custom-control-input" id="customSwitch1" name="removepunc">
                  <label class="custom-control-label" for="customSwitch1">Remove Punctuation</label>
                </div>
                <div class="custom-control custom-switch">
                  <input type="checkbox" class="custom-control-input" id="customSwitch2" name="uppercase">
                  <label class="custom-control-label" for="customSwitch2">UPPERCASE</label>
                </div>
                <div class="custom-control custom-switch">
                  <input type="checkbox" class="custom-control-input" id="customSwitch3" name="newlineremover">
                  <label class="custom-control-label" for="customSwitch3">New Line Remover</label>
                </div>
                <div class="custom-control custom-switch">
                  <input type="checkbox" class="custom-control-input" id="customSwitch4" name="extraspaceremover">
                  <label class="custom-control-label" for="customSwitch4">Extra Space Remover</label>
                </div>
                 <button type="submit" class="btn btn-dark mt-2">Analyze Text</button>
            </form>
        </div>
    </div>

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}
Login | Page
{% endblock %}

{% block content %}
<h1> This is Login page</h1>



<form class="site-form" action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}
    {{ form }}

    {% if request.GET.next %}
        <input type="hidden" name="next" value="{{ request.GET.next }}" >
    {% endif %}

    <input type="submit" value="login">

</form>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}
SignUp | Page
{% endblock %}

{% block content %}

<h1>Sign Up</h1>
<form class="site-form" action="/accounts/signup/" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="signup">

</form>

{% endblock %}